In [4]:
import calendar

print(calendar.__doc__)

Calendar printing functions

Note when comparing these calendars to the ones printed by cal(1): By
default, these calendars have Monday as the first day of the week, and
Sunday as the last (the European convention). Use setfirstweekday() to
set the first day of the week (0=Monday, 6=Sunday).


In [5]:
import time

# time.time()
time.localtime()
# time.asctime()
# time.ctime()

time.struct_time(tm_year=2022, tm_mon=4, tm_mday=7, tm_hour=21, tm_min=54, tm_sec=30, tm_wday=3, tm_yday=97, tm_isdst=0)

In [6]:
from datetime import datetime

delta = datetime(2022,4,6) - datetime(2022, 1,1)


In [7]:
import numpy as np

a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
a.dtype

dtype('float64')

In [9]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
na = np.array(np.arange(24), dtype=int).reshape(4, 6)
na

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
na[:2, 1:3]

array([[1, 2],
       [7, 8]])

In [15]:
na1 = na.reshape(2,3,4)
na1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
a1 = np.array(np.arange(5))
np.add(a1, 4)
np.add(a1, 4, a1)
a1

array([4, 5, 6, 7, 8])